apiVersion: v1
kind: Service
metadata:  
  name: datacollector
  namespace: liwei1dao
  labels:  
    app: datacollector
spec:  
  selector:  
    app: datacollector
  ports:  
  - name: http  
    protocol: TCP  
    port: 80  
    targetPort: 8080  